# Generated by Django 2.0.1 on 2018-01-15 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('PD', 'Pending'), ('DN', 'Done')], default='PD', max_length=2)),
            ],
            options={
                'ordering': ('query',),
            },
        ),
        migrations.CreateModel(
            name='TwitterProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tw_id', models.PositiveIntegerField(unique=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.URLField(blank=True, null=True)),
                ('popularity', models.PositiveIntegerField(blank=True, default=0)),
            ],
            options={
                'ordering': ('popularity', 'name'),
            },
        ),
    ]
